absolute_urls: false
timezone: America/Toronto
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
languages:
  include_default_lang: true
  translations: false
  translations_fallback: false
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /home
  hide_in_urls: false
pages:
  theme: kkca
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: 'm/d/Y h:i a'
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: true
  twig_first: false
  events:
    page: true
    twig: true
  markdown:
    extra: true
    auto_line_breaks: true
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: true
  redirect_default_code: '301'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: false
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: true
  js_minify: true
  enable_asset_timestamp: false
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: true
  log: true
debugger:
  enabled: false
  shutdown:
    close_connection: true
images:
  default_image_quality: 85
  cache_all: true
  cache_perms: '0755'
  debug: false
media:
  enable_media_timestamp: true
  upload_limit: 0
session:
  enabled: true
  timeout: 1800
  name: kkurucz-site
  secure: true
  httponly: true
