title: York Region Acoustic Open Mic

author:
  name: Steffi Goodfield
  email: 'folkrocksing@gmail.com'
  footer: Support Live Music! Be The Live Music!
metadata:
    description: 'Metadata here!'

# Main Menu
menu:

social: 
  - icon: socicon-mail 
    link: "mailto:.com" 
  - icon: socicon-twitter
    link: "http://twitter.com" 
  - icon: socicon-facebook
    link: "http://facebook.com" 
  - icon: socicon-instagram
    link: "http://instagram.com"